# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

sudo:
  - true

dist:
  - trusty

group: deprecated-2017Q3

install:
  # Info about OS
  - uname -a

script:
  - which pip3
  - pip3 --version

# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - /^pr\..*/
